import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import HydrationZustand from "@/components/Global/HydrationZustand";
import NextUi from "@/components/Global/NextUi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUi>
          <HydrationZustand LoaderComponent={<div>Loading...</div>}>
            <Sidebar />
            {children}
          </HydrationZustand>
        </NextUi>
      </body>
    </html>
  );
}
